# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require File.expand_path('../config/application', __FILE__)

require 'rake/extensiontask'
require 'rake/javaextensiontask'

Rake::ExtensionTask.new('prime_c_demo')
Rake::JavaExtensionTask.new('prime_java_demo')

Rails.application.load_tasks
