# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c5a7af4465c66291c18f2f01f363c9bca18de79f5456d6c0ce0df56f6c43fa915640f8076ccf5380c6a02c7da1172574c170989b4388278d9ecac282dd5b5f67

test:
  secret_key_base: da52657b0c83a2015a8f4b8df5e493e5c1954c00441b5a08552a5b580de76b5ac516d5010ab38c8d597170eddb1c5bd921b159ce50f2d83150d68ef5df32df1e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
